/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppRoot {
    }
    interface AppTabs {
    }
    interface PageDraw {
    }
    interface PageHome {
    }
    interface PagePeopleList {
    }
    interface PageProfile {
        "peopleId": number;
    }
}
declare global {
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLAppTabsElement extends Components.AppTabs, HTMLStencilElement {
    }
    var HTMLAppTabsElement: {
        prototype: HTMLAppTabsElement;
        new (): HTMLAppTabsElement;
    };
    interface HTMLPageDrawElement extends Components.PageDraw, HTMLStencilElement {
    }
    var HTMLPageDrawElement: {
        prototype: HTMLPageDrawElement;
        new (): HTMLPageDrawElement;
    };
    interface HTMLPageHomeElement extends Components.PageHome, HTMLStencilElement {
    }
    var HTMLPageHomeElement: {
        prototype: HTMLPageHomeElement;
        new (): HTMLPageHomeElement;
    };
    interface HTMLPagePeopleListElement extends Components.PagePeopleList, HTMLStencilElement {
    }
    var HTMLPagePeopleListElement: {
        prototype: HTMLPagePeopleListElement;
        new (): HTMLPagePeopleListElement;
    };
    interface HTMLPageProfileElement extends Components.PageProfile, HTMLStencilElement {
    }
    var HTMLPageProfileElement: {
        prototype: HTMLPageProfileElement;
        new (): HTMLPageProfileElement;
    };
    interface HTMLElementTagNameMap {
        "app-root": HTMLAppRootElement;
        "app-tabs": HTMLAppTabsElement;
        "page-draw": HTMLPageDrawElement;
        "page-home": HTMLPageHomeElement;
        "page-people-list": HTMLPagePeopleListElement;
        "page-profile": HTMLPageProfileElement;
    }
}
declare namespace LocalJSX {
    interface AppRoot {
    }
    interface AppTabs {
    }
    interface PageDraw {
    }
    interface PageHome {
    }
    interface PagePeopleList {
    }
    interface PageProfile {
        "peopleId"?: number;
    }
    interface IntrinsicElements {
        "app-root": AppRoot;
        "app-tabs": AppTabs;
        "page-draw": PageDraw;
        "page-home": PageHome;
        "page-people-list": PagePeopleList;
        "page-profile": PageProfile;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "app-tabs": LocalJSX.AppTabs & JSXBase.HTMLAttributes<HTMLAppTabsElement>;
            "page-draw": LocalJSX.PageDraw & JSXBase.HTMLAttributes<HTMLPageDrawElement>;
            "page-home": LocalJSX.PageHome & JSXBase.HTMLAttributes<HTMLPageHomeElement>;
            "page-people-list": LocalJSX.PagePeopleList & JSXBase.HTMLAttributes<HTMLPagePeopleListElement>;
            "page-profile": LocalJSX.PageProfile & JSXBase.HTMLAttributes<HTMLPageProfileElement>;
        }
    }
}
