/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppRoot {
    }
    interface AppTabs {
    }
    interface PageDraw {
        "groupId": number;
    }
    interface PageGroupList {
    }
    interface PagePersonList {
    }
    interface PageProfile {
        "personId": number;
    }
}
declare global {
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLAppTabsElement extends Components.AppTabs, HTMLStencilElement {
    }
    var HTMLAppTabsElement: {
        prototype: HTMLAppTabsElement;
        new (): HTMLAppTabsElement;
    };
    interface HTMLPageDrawElement extends Components.PageDraw, HTMLStencilElement {
    }
    var HTMLPageDrawElement: {
        prototype: HTMLPageDrawElement;
        new (): HTMLPageDrawElement;
    };
    interface HTMLPageGroupListElement extends Components.PageGroupList, HTMLStencilElement {
    }
    var HTMLPageGroupListElement: {
        prototype: HTMLPageGroupListElement;
        new (): HTMLPageGroupListElement;
    };
    interface HTMLPagePersonListElement extends Components.PagePersonList, HTMLStencilElement {
    }
    var HTMLPagePersonListElement: {
        prototype: HTMLPagePersonListElement;
        new (): HTMLPagePersonListElement;
    };
    interface HTMLPageProfileElement extends Components.PageProfile, HTMLStencilElement {
    }
    var HTMLPageProfileElement: {
        prototype: HTMLPageProfileElement;
        new (): HTMLPageProfileElement;
    };
    interface HTMLElementTagNameMap {
        "app-root": HTMLAppRootElement;
        "app-tabs": HTMLAppTabsElement;
        "page-draw": HTMLPageDrawElement;
        "page-group-list": HTMLPageGroupListElement;
        "page-person-list": HTMLPagePersonListElement;
        "page-profile": HTMLPageProfileElement;
    }
}
declare namespace LocalJSX {
    interface AppRoot {
    }
    interface AppTabs {
    }
    interface PageDraw {
        "groupId"?: number;
    }
    interface PageGroupList {
    }
    interface PagePersonList {
    }
    interface PageProfile {
        "personId"?: number;
    }
    interface IntrinsicElements {
        "app-root": AppRoot;
        "app-tabs": AppTabs;
        "page-draw": PageDraw;
        "page-group-list": PageGroupList;
        "page-person-list": PagePersonList;
        "page-profile": PageProfile;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "app-tabs": LocalJSX.AppTabs & JSXBase.HTMLAttributes<HTMLAppTabsElement>;
            "page-draw": LocalJSX.PageDraw & JSXBase.HTMLAttributes<HTMLPageDrawElement>;
            "page-group-list": LocalJSX.PageGroupList & JSXBase.HTMLAttributes<HTMLPageGroupListElement>;
            "page-person-list": LocalJSX.PagePersonList & JSXBase.HTMLAttributes<HTMLPagePersonListElement>;
            "page-profile": LocalJSX.PageProfile & JSXBase.HTMLAttributes<HTMLPageProfileElement>;
        }
    }
}
